Repository container-mgmt/messaging-library, pull requests merged in 2018-06, with the labels that each got.

#3 Add lint to makefile
  Makefile
  pkg/client/client.go
Labels: ci enhancment

#5 Rename files using struct name
  pkg/client/client.go
  pkg/client/connection.go
  pkg/client/stomp_connection.go
Labels: infrastructure prototyping

#4 Add a stub message for prototyping
  pkg/client/message.go
Labels: infrastructure prototyping

#8 Disconnect instead of close
  pkg/client/connection.go
  pkg/client/stomp_connection.go
Labels: infrastructure prototyping

#9 Make configuration parameters global
  pkg/client/message.go
  pkg/client/stomp_connection.go
Labels: infrastructure prototyping

#11 Add a make binaries option
  Makefile
  build
Labels: infrastructure prototyping

#12 Explicit message
  pkg/client/message.go
Labels: infrastructure prototyping

#14 remove unneaded var from message stub struct
  pkg/client/message.go
Labels: infrastructure prototyping

#15 Fix indentation in build script build binaries function
  build
Labels: bug, ci enhancment

#7 Add binary example
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  cmd/messaging-tool/main.go
  cmd/messaging-tool/receive.go
  cmd/messaging-tool/send.go
Labels: enhancement

#22 Add builder to connection implementation
  cmd/messaging-tool/receive.go
  cmd/messaging-tool/send.go
  pkg/connections/stomp/connection.go
  pkg/connections/stomp/connection_builder.go
  pkg/connections/stomp/publish.go
  pkg/connections/stomp/subscribe.go
Labels: infrastructure prototyping

#23 Update readme
  CHANGES.md
  README.adoc
  README.md
Labels: documentation

#24 Use adoc for readme
  CHANGES.adoc
  README.adoc
Labels: documentation

#25 Update comments for publish subscribe interface
  pkg/client/connection.go
Labels: documentation

#27 Use topic instead of destination
  README.adoc
  cmd/messaging-tool/main.go
  cmd/messaging-tool/receive.go
  cmd/messaging-tool/send.go
Labels: bug

#29 Godoc wants only one docstring per package
  README.adoc
  pkg/client/message.go
  pkg/connections/stomp/connection.go
Labels: documentation

#28 Use destination instead of topic
  README.adoc
  cmd/messaging-tool/main.go
  cmd/messaging-tool/receive.go
  cmd/messaging-tool/send.go
  pkg/client/connection.go
  pkg/connections/stomp/publish.go
  pkg/connections/stomp/subscribe.go
Labels: infrastructure prototyping

#26 Add error to message
  cmd/messaging-tool/main.go
  cmd/messaging-tool/receive.go
  pkg/client/message.go
  pkg/connections/stomp/subscribe.go
Labels: infrastructure prototyping

#30 Fix spelling
  pkg/connections/stomp/connection.go
Labels: bug, documentation

#31 Add a STOMP server example
  Gopkg.lock
  cmd/messaging-server/main.go
  cmd/messaging-server/serve.go
Labels: ci enhancment

#32 Add run examples to readme
  README.adoc
  cmd/messaging-server/README.adoc
  cmd/messaging-tool/README.adoc
Labels: documentation

#34 Fix ineffectual assignment of bodyBytes
  cmd/messaging-tool/send.go
Labels: bug, examples

#35 Fix return value from callback in send example
  cmd/messaging-tool/receive.go
Labels: bug, examples

#36 More documentaion
  README.adoc
  pkg/client/connection.go
  pkg/client/message.go
  pkg/connections/stomp/connection.go
  pkg/connections/stomp/connection_builder.go
  pkg/connections/stomp/publish.go
  pkg/connections/stomp/subscribe.go
Labels: documentation

#33 Add unsubscibe
  cmd/messaging-tool/receive.go
  pkg/client/connection.go
  pkg/connections/stomp/connection.go
  pkg/connections/stomp/connection_builder.go
  pkg/connections/stomp/subscribe.go
Labels: infrastructure prototyping

#37 Use json message body
  README.adoc
  cmd/messaging-tool/receive.go
  cmd/messaging-tool/send.go
  pkg/client/message.go
  pkg/connections/stomp/publish.go
  pkg/connections/stomp/subscribe.go
Labels: enhancement, infrastructure prototyping

#38 Add message content type
  README.adoc
  cmd/messaging-tool/send.go
  pkg/client/connection.go
  pkg/client/message.go
  pkg/connections/stomp/subscribe.go
Labels: enhancement, infrastructure prototyping

#39 Add a low level publish function
  README.adoc
  cmd/messaging-tool/receive.go
  cmd/messaging-tool/send.go
  pkg/client/connection.go
  pkg/client/message.go
  pkg/connections/stomp/publish.go
Labels: bug, enhancement, infrastructure prototyping

#40 Fix typos
  pkg/client/connection.go
  pkg/connections/stomp/publish.go
  pkg/connections/stomp/subscribe.go
Labels: bug, documentation

#41 Add a spell checker to the travis ci
  .travis.yml
Labels: ci enhancment

#42 Add inline documentation to send example
  README.adoc
  cmd/messaging-tool/send.go
  pkg/client/connection.go
  pkg/client/message.go
Labels: documentation

#43 In case of jason parse error return the raw data to user
  pkg/connections/stomp/subscribe.go
Labels: enhancement, infrastructure prototyping

#45 Add example to connection stomp docstring
  pkg/client/connection.go
  pkg/connections/stomp/connection.go
  pkg/connections/stomp/connection_builder.go
Labels: documentation

#46 Fix godoc links
  README.adoc
  pkg/connections/stomp/connection_builder.go
Labels: documentation

#47 Add tests
  pkg/connections/stomp/connection.go
  pkg/connections/stomp/connection_test.go
Labels: ci enhancment, tests

#55 Fix sync subscirbe
  cmd/messaging-tool/receive.go
  pkg/connections/stomp/connection_test.go
  pkg/connections/stomp/subscribe.go
Labels: bug, infrastructure prototyping, tests

#56 Add benchmark to makefile, and update tests
  Makefile
  build.py
  pkg/connections/stomp/connection_test.go
Labels: bug, ci enhancment, tests

#59 Update readme file to include running tests
  README.adoc
Labels: documentation

#61 Add a run-time test
  README.adoc
  pkg/connections/stomp/connection_test.go
Labels: tests

#62 Add -set_exit_status flag to golint
  build.py
  pkg/connections/stomp/connection_test.go
Labels: bug, ci enhancment

#63 Fix lint and fmt in build py script
  build.py
Labels: bug, ci enhancment

#65 Add a travis test for fmt
  .travis.yml
  build.py
Labels: bug, ci enhancment

#66 Remove the `find_paths` function from `build.py`
  build.py
Labels: bug, ci enhancment

#67 Adding pylint to travis
  .travis.yml
  build.py
Labels: ci enhancment
